Allow setting root directory when reading from STDIN
phadej/cabal-fmt pull request #65
Opened 2023-01-04 17:12 UTC by tfausak

Fixes #51.

This adds a new `--root DIR` option to the CLI. When reading input from STDIN, if the `--root` option is set, the `DIR` will be used when finding modules as part of the `-- cabal-fmt: expand some-directory` pragma. For example:

``` sh
# Works the same as before.
cabal-fmt some-package.cabal

# Also works the same as before. The `--root` option is silently ignored.
cabal-fmt --root ignored some-package.cabal

# Works the same as before. No root directory is set, so no expanding happens.
cabal-fmt < some-package.cabal

# New behavior! Root directory is set, so expanding happens even though we're reading from STDIN.
cabal-fmt --root . < some-package.cabal
```

2023-01-04 17:19 UTC, phadej requested changes
Not a fan of silently ignoring the root. Better to forbid its usage with filepaths (in `main`).

2023-01-04 17:19 UTC, phadej commented on cli/Main.hs
> +    let root = maybe (optRoot opts) Just $ fmap takeDirectory mfilepath
`takeDirectory <$> mfilepath <|> optRoot opts`

2023-01-04 17:33 UTC, tfausak commented
Agreed! See 563cdecf639be0132c9de70e0824f748d8267d95 for that change. Now if you try to pass both, it will fail:

``` sh
$ cabal-fmt --root invalid some-package.cabal
error: cannot pass both --root and FILE
```

2023-01-16 13:40 UTC, tfausak commented
Please let me know if you need anything else from me to move this along. Thanks!

2023-07-27 17:50 UTC, tfausak commented
I'm closing this in favor of #82.

2023-07-27 17:50 UTC, closed without merging